### ISSUE TITLE
The caculteProbability funtion detect

### ISSUE THREAD

**Issue by muare** [MinhasKamal/SkinDetector#2]
the original implementation is :
probability = skinPixelNumber[i][j][k]*probabilityOfSkin/(skinPixelNumber[i][j][k]+nonskinPixelNumber[i][j][k]);

it should be conditional probaility;
probability = skinPixelNumber[i][j][k]/totalSkinPixelNumber*probabilityOfSkin/(skinPixelNumber[i][j][k]/totalSkinPixelNumber*probabilityOfSkin+nonskinPixelNumber[i][j][k]/totalNonskinPixelNumber*(1-probabilityOfSkin));

or

probability  = skinPixelNumber[i][j][k]/(skinPixelNumber[i][j][k]+nonskinPixelNumber[i][j][k])

**Comment by MinhasKamal** [comment]
Your equation will only produce- `probability of the pixel being skin`
However we want to find- `probability of a skin pixel = probability of the pixel being skin * probability of skin`
Please see [Bayesian Theorem](https://en.wikipedia.org/wiki/Bayes%27_theorem) for details.
